config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'pages#home'

  namespace :admin do
    resources :collectors
    resources :forms
    resources :form_responses, only: [:show]
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :forms, only: [:index]
      resources :sessions, only: [:create,:destroy]
      resources :form_responses, only: [:create]
      resources :sessions, only: [:create] do
        collection do
          delete :destroy
        end
      end
    end
  end

end

app/controllers/admin/collectors_controller.rb
class Admin::CollectorsController < ApplicationController
  before_action :authenticate_user!
  before_filter :company_permission

  def new
    @collector = current_company.users.build
  end

  def create
    @collector = current_company.users.build(collector_params)
    generated_password = Devise.friendly_token.first(8)
    @collector.password = generated_password
    @collector.role = User.roles[:info_collector]
    if @collector.save
      flash[:notice] = "El asesor móvil #{@collector.first_name} #{@collector.last_name} fue creado con éxito"
      redirect_to admin_collectors_path
    else
      flash[:alert] = "Ha ocurrido un error y el asesor móvil #{@collector.first_name} #{@collector.last_name}, no ha sido almacenado"
      render :action => 'new'
    end
  end

  def edit
    @collector = current_company.users.find(params[:id])
  end

  def update
    @collector = current_company.users.find(params[:id])
    if @collector.update(collector_params)
      flash[:notice] = "El asesor móvil #{@collector.first_name} #{@collector.last_name} ha sido editado con éxito"
      redirect_to admin_collectors_path
    else
      flash[:alert] = 'Ha ocurrido un error y el asesor móvil #{@collector.first_name} #{@collector.last_name}, no ha sido editado'
      render 'edit'
    end
  end

  def index
    @collectors = current_company.users.where(role: User.roles[:info_collector])
  end

  def destroy
    @collector = current_company.users.find(params[:id])
    @collector.destroy
    redirect_to admin_collectors_path
  end

  private
    def collector_params
      params.require(:user).permit(:first_name, :last_name, :email, :id_number, :avatar)
    end

    def company_permission
      unless current_user.admin?
        redirect_to root_path, :alert => "Lo sentimos, usted no posee permisos de administrador para acceder a esta ruta."
      end
    end
end

app/helpers/admin/collectors_helper.rb
module Admin::CollectorsHelper
end

app/views/admin/collectors/_form.html.erb
<div class="col-md-6 col-md-offset-3">
  <% if @collector.new_record? %>
    <% path = admin_collectors_path %>
  <% else %>
    <% path = admin_collector_path(@collector) %>
  <% end %>
  <%= form_for(@collector, url: path) do |collector| %>
    <% if @collector.errors.any? %>
      <% @collector.errors.each do |attribute, message| %>
        <h3 class="validation-error"><%= attribute %> <%= message %></h3>
      <% end %>
    <% end %>

    <div class="field form-group">
      <%= collector.label :first_name, "Nombre", class: "lead lead-lg"  %>
      <%= collector.text_field :first_name, class: "form-control", id: "password" %>
    </div>

    <div class="field form-group">
      <%= collector.label :last_name, "Apellidos", class: "lead lead-lg"  %>
      <%= collector.text_field :last_name, class: "form-control", id: "password" %>
    </div>

    <div class="field form-group">
      <%= collector.label :email, "Correo Electrónico:", class: "lead lead-lg" %>
      <%= collector.email_field :email, required: true, :rows => 5, class: "form-control", id: "new_user_email" %>
    </div>

    <div class="field form-group">
      <%= collector.label :id_number, "Documento de Identidad:", class: "lead lead-lg"  %>
      <%= collector.text_field :id_number, class: "form-control", id: "password" %>
    </div>

    <% if collector.object.avatar.url != "http://i592.photobucket.com/albums/tt5/Mardini03/imagen-no-disponible.png" %>
      <div class="row">
        <div class="col-md-3 col-sm-4 col-xs-4 edit_images">
          <%= image_tag collector.object.avatar.url(:mini_thumb) %>
        </div>

        <div class="col-md-9 col-sm-8 col-xs-8">
          <%= collector.label :id_number, "Imágen de perfil:", class: "lead lead-lg"  %>
          <div class="col-md-9 col-sm-9 col-xs-9">
            <div class="form-group reg-email">
              <div>
                <%= collector.file_field :avatar, class: "input-file" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% else %>
      <div class="field form-group">
        <%= collector.label :id_number, "Imágen de perfil:", class: "lead lead-lg"  %>
        <%= collector.file_field :avatar, required: true, class: "input-file form-control" %>
      </div>
    <% end %>

    <div class="row" style="margin-top: 20px;">
      <div class="actions form-group text-center">
        <%= collector.submit "Guardar Información", class: "btn btn-ar btn-lg btn-success" %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/collectors/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h2 class="text-center">Editar Asesor móvil</h2>
    </div>
  </div>
  <%= render 'form' %>
</div>

app/views/admin/collectors/index.html.erb
<div class="container">
  <div class="row">
    <% @collectors.each do |collector| %>
      <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
          <img src="<%= collector.avatar.url(:thumb) %>" alt="..." class="img-responsive">
          <div class="caption">
            <h3>Asesor Móvil</h3>
            <p><%= "#{collector.first_name} #{collector.last_name} " %></p>
            <p><%= link_to "Editar", edit_admin_collector_path(collector), class: "btn btn-warning" %>  <%= link_to "Eliminar", admin_collector_path(collector), method: :delete, data: { confirm: '¿Esta seguro que desea eliminarlo?' }, class: "btn btn-danger" %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/collectors/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h2 class="text-center">Nuevo Asesor móvil</h2>
    </div>
  </div>
  <%= render 'form' %>
</div>