config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'pages#home'

  namespace :admin do
    resources :collectors
    resources :forms
    resources :form_responses, only: [:show]
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :forms, only: [:index]
      resources :sessions, only: [:create,:destroy]
      resources :form_responses, only: [:create]
      resources :sessions, only: [:create] do
        collection do
          delete :destroy
        end
      end
    end
  end

end

app/controllers/admin/forms_controller.rb
class Admin::FormsController < ApplicationController

  def index
    @forms = current_company.forms.all
  end

  def new
    @form = current_company.forms.build
  end

  def edit
    @form = current_company.forms.find(params[:id])
    @questions = @form.questions
  end

  def update
    @form = current_company.forms.find(params[:id])
    if @form.update(form_params)
      flash[:notice] = "El formulario #{@form.name} fue actualizado con éxito"
      redirect_to admin_forms_path
    else
      flash[:alert] = "Ha ocurrido un error y el formulario #{@form.name}, no ha sido actualizado"
      render :action => 'edit'
    end
  end

  def show
    @form = current_company.forms.find(params[:id])
    @form_responses = @form.form_responses
  end

  def create
    @form = current_company.forms.build(form_params)
    if @form.save
      flash[:notice] = "El formulario #{@form.name} fue creado con éxito"
      redirect_to admin_forms_path
    else
      flash[:alert] = "Ha ocurrido un error y el formulario #{@form.name}, no ha sido almacenado"
      render :action => 'new'
    end
  end

  def destroy
    form = current_company.forms.find(params[:id])
    form.destroy
    redirect_to admin_forms_path
  end

  private
    def form_params
      params.require(:form).permit(:name, :description, questions_attributes: [:id, :text, :question_type, :_destroy, question_options_attributes: [:id, :text, :_destroy]])
    end
end

app/controllers/api/v1/forms_controller.rb
class Api::V1::FormsController < Api::V1::ApiController
  before_action :authenticate_with_token!

  def index
    render json: current_company.forms
  end

end

app/helpers/admin/forms_helper.rb
module Admin::FormsHelper
end

app/views/admin/forms/_form.html.erb
<% if @form.new_record? %>
  <% path = admin_forms_path %>
<% else %>
  <% path = admin_form_path(@form) %>
<% end %>
<%= form_for(@form, url: path) do |form| %>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1 class="text-center">Nuevo Formulario</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
        <h2 class="text-center">Tipo de pregunta</h2>
        <% Question.question_types.keys.each do |question_type| %>
          <div class="panel panel-default">
            <%= link_to_add_association form, :questions, partial: "admin/forms/question_fields_#{question_type}", class: "add-new-question question-type-option" do %>
              <div class="panel-body"><%= t("question_type.#{question_type}") %></div>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="col-md-8" id="questions-container">
        <% if @form.errors.any? %>
          <% @form.errors.each do |attribute, message| %>
            <h3 class="validation-error"><%= attribute %> <%= message %></h3>
          <% end %>
        <% end %>
        <div class="form-group">
          <label for="exampleInputName2">Nombre del formulario</label>
          <%= form.text_field :name, placeholder: 'Nombre del formulario', class: 'form-control' %>
        </div>
        <div class="form-group">
          <label for="exampleInputEmail2">Descripción del formulario</label>
          <%= form.text_field :description, placeholder: 'Descripción del formulario', class: 'form-control' %>
        </div>
        <%= form.fields_for :questions do |question_form| %>
          <% question = question_form.object %>
          <%= render "admin/forms/question_fields_#{question.question_type}", f: question_form %>
        <% end %>

      </div>
      <div class="row" style="margin-top: 20px;">
        <div class="actions form-group text-center">
          <%= form.submit "Guardar Formulario", class: "btn btn-ar btn-lg btn-success" %>
        </div>
      </div>
    </div>
    <%#= render 'form' %>
  </div>

<% end %>

<style>
  .panel-default:hover {
    background-color: #dfdfdf !important;
  }
</style>

<script>
  (function(){
    var setupCocoon = function() {
      $("a.add-new-question").
        data("association-insertion-method", 'append').
        data("association-insertion-node", '#questions-container');
    }
    $(document).on('ready',setupCocoon);
    $(document).on('page:load',setupCocoon);
  })()
</script>

app/views/admin/forms/_question_fields_checkbox.html.erb
<div class="col-md-12 nested-fields">
  <h4><%= t('question_type.checkbox') %></h4>
  <div class="col-md-10">
    <%= f.text_field :text, class: "form-control" %>
    <%= f.hidden_field :question_type, :value => :checkbox %>
  </div>

  <div class="col-md-2">
    <%= link_to_remove_association "<i class='glyphicon glyphicon-trash'></i>".html_safe, f, class: "btn btn-danger"%>
  </div>

  <div class="field form-group">
    <% f.object.question_options.build if f.object.question_options.empty? %>
    <%= f.fields_for :question_options do |question_option| %>
      <%= render 'admin/forms/question_option_fields', f: question_option %>
      <%= link_to_add_association 'Agregar Opción', f, :question_options %>
    <% end %>
  </div>
</div>

app/views/admin/forms/_question_fields_dropdown.html.erb
<div class="col-md-12 nested-fields margin-bottom">
  <div class="field form-group">
    <h4><%= t('question_type.dropdown') %></h4>
    <div class="col-md-10 col-sm-9 col-xs-9">
      <%= f.text_field :text, class: "form-control" %>
      <%= f.hidden_field :question_type, :value => :dropdown %>
    </div>

    <div class="col-md-2 col-sm-3 col-xs-3">
      <%= link_to_remove_association "<i class='glyphicon glyphicon-trash'></i>".html_safe, f, class: "btn btn-danger"%>
    </div>

  </div>

  <div class="field form-groyp">
    <% f.object.question_options.build if f.object.question_options.empty? %>
    <%= f.fields_for :question_options do |question_option| %>
      <%= render 'admin/forms/question_option_fields', f: question_option %>
      <%= link_to_add_association 'Agregar Opción', f, :question_options %>
    <% end %>
  </div>
</div>

app/views/admin/forms/_question_fields_image.html.erb
<div class="col-md-12 nested-fields margin-bottom">
  <h4><%= t('question_type.image') %></h4>
  <div class="col-md-10 col-sm-9 col-xs-9">
    <%= f.text_field :text, class: "form-control", id: "password" %>
    <%= f.hidden_field :question_type, :value => :image %>
  </div>

  <div class="col-md-2 col-sm-3 col-xs-3">
    <%= link_to_remove_association "<i class='glyphicon glyphicon-trash'></i>".html_safe, f, class: "btn btn-danger"%>
  </div>
</div>

app/views/admin/forms/_question_fields_input.html.erb
<div class="col-md-12 nested-fields margin-bottom">
  <h4><%= t('question_type.input') %></h4>
  <div class="col-md-10 col-sm-9 col-xs-9">
    <%= f.text_field :text, class: "form-control", id: "password" %>
    <%= f.hidden_field :question_type, :value => :input %>
  </div>

  <div class="col-md-2 col-sm-3 col-xs-3">
    <%= link_to_remove_association "<i class='glyphicon glyphicon-trash'></i>".html_safe, f, class: "btn btn-danger"%>
  </div>
</div>

app/views/admin/forms/_question_fields_long_open_answer.html.erb
<div class="col-md-12 nested-fields margin-bottom">
  <h4>Pregunta de extensa respuesta abierta</h4>
  <div class="col-md-10 col-sm-9 col-xs-9">
    <%= f.text_field :text, class: "form-control" %>
    <%= f.hidden_field :question_type, :value => :text %>
  </div>

  <div class="col-md-2 col-sm-3 col-xs-3">
    <%= link_to_remove_association "<i class='glyphicon glyphicon-trash'></i>".html_safe, f, class: "btn btn-danger"%>
  </div>
</div>

app/views/admin/forms/_question_fields_multiple_selection.html.erb
<div class="col-md-12 nested-fields">
  <h4>Pregunta de selección multiple</h4>
  <div class="col-md-10">
    <%= f.text_field :text, class: "form-control" %>
    <%= f.hidden_field :question_type, :value => :checkbox %>
  </div>

  <div class="col-md-2">
    <%= link_to_remove_association "<i class='glyphicon glyphicon-trash'></i>".html_safe, f, class: "btn btn-danger"%>
  </div>

  <div class="field form-group">
    <% f.object.question_options.build if f.object.question_options.empty? %>
    <%= f.fields_for :question_options do |question_option| %>
      <%= render 'admin/forms/question_option_fields', f: question_option %>
      <%= link_to_add_association 'Agregar Opción', f, :question_options %>
    <% end %>
  </div>
</div>

app/views/admin/forms/_question_fields_short_open_answer.html.erb
<div class="col-md-12 nested-fields margin-bottom">
  <h4>Pregunta de corta respuesta abierta</h4>
  <div class="col-md-10 col-sm-9 col-xs-9">
    <%= f.text_field :text, class: "form-control", id: "password" %>
    <%= f.hidden_field :question_type, :value => :input %>
  </div>

  <div class="col-md-2 col-sm-3 col-xs-3">
    <%= link_to_remove_association "<i class='glyphicon glyphicon-trash'></i>".html_safe, f, class: "btn btn-danger"%>
  </div>
</div>

app/views/admin/forms/_question_fields_text.html.erb
<div class="col-md-12 nested-fields margin-bottom">
  <h4><%= t('question_type.text') %></h4>
  <div class="col-md-10 col-sm-9 col-xs-9">
    <%= f.text_field :text, class: "form-control" %>
    <%= f.hidden_field :question_type, :value => :text %>
  </div>

  <div class="col-md-2 col-sm-3 col-xs-3">
    <%= link_to_remove_association "<i class='glyphicon glyphicon-trash'></i>".html_safe, f, class: "btn btn-danger"%>
  </div>
</div>

app/views/admin/forms/_question_fields_unique_option.html.erb
<div class="col-md-12 nested-fields margin-bottom">
  <div class="field form-group">
    <h4>Pregunta de única respuesta</h4>
    <div class="col-md-10 col-sm-9 col-xs-9">
      <%= f.text_field :text, class: "form-control" %>
      <%= f.hidden_field :question_type, :value => :dropdown %>
    </div>

    <div class="col-md-2 col-sm-3 col-xs-3">
      <%= link_to_remove_association "<i class='glyphicon glyphicon-trash'></i>".html_safe, f, class: "btn btn-danger"%>
    </div>

  </div>

  <div class="field form-groyp">
    <% f.object.question_options.build if f.object.question_options.empty? %>
    <%= f.fields_for :question_options do |question_option| %>
      <%= render 'admin/forms/question_option_fields', f: question_option %>
      <%= link_to_add_association 'Agregar Opción', f, :question_options %>
    <% end %>
  </div>
</div>

app/views/admin/forms/_question_option_fields.html.erb
<div class="col-md-12 nested-fields margin-bottom">
<h4>Opción</h4>
  <div class="field form-group">
    <div class="col-md-8 col-sm-8 col-xs-8">
      <%= f.text_field :text, class: "form-control" %>
      <%= f.hidden_field :question_type, :value => :dropdown %>
    </div>

    <div class="col-md-2 col-sm-3 col-xs-3">
      <%= link_to_remove_association "<i class='glyphicon glyphicon-trash'></i>".html_safe, f, class: "btn btn-danger"%>
    </div>
  </div>
</div>

app/views/admin/forms/edit.html.erb
<%= render 'form' %>

app/views/admin/forms/index.html.erb
<div class="container">
  <h1 class="margin-bottom">Lista de formularios</h1>
  <hr>
  <div class="row">
    <% @forms.each do |form| %>
      <div class="col-sm-6 col-md-6">
        <div class="thumbnail">
          <div class="caption">
            <%= link_to admin_form_path(form), method: :delete, data: { confirm: '¿Esta seguro que desea eliminarlo?' } do %>
              <i data-toggle="tooltip" data-placement="top" title="Eliminar" class="pull-right glyphicon glyphicon-trash" style="color: #DD4B39"></i>
            <% end %>
            <%= link_to edit_admin_form_path(form) do %>
              <i data-toggle="tooltip" data-placement="top" title="Editar" class="pull-right glyphicon glyphicon-pencil margin-right" style="color: #42C0FB"></i>
            <% end %>
            <h4><%= form.name %></h4>
            <p><%= form.description %></p>
            <p>
              <%= link_to "Ver Respuestas", admin_form_path(form), class: "btn btn-success" %>
             </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<script>
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })
</script>

app/views/admin/forms/show.html.erb
<div class="container">
  <h2><%= @form.name %></h2>
  <div class="box-body row">
    <div class="table-responsive col-md-12">
      <table class="table no-margin">
        <thead>
          <tr>
            <% @form.questions.limit(5).each do |question| %>
              <th><%= question.text %></th>
            <% end %>
              <th>Ver</th>
          </tr>
        </thead>
        <tbody>
          <% @form.form_responses.each do |form_response| %>
          <tr>
            <% form_response.question_responses.limit(5).each do |question_response| %>
              <td>
                <% if question_response.question.image? %>
                  <%= image_tag question_response.image.url(:thumb) %>
                <% else %>
                  <%= question_response.to_s %>
                <% end %>
              </td>
            <% end %>
              <td>
                <%= link_to admin_form_response_path(form_response) do %>
                  <i class="glyphicon glyphicon-eye-open"></i>
                <% end %>
              </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to admin_forms_path do %>
        <button type="button" class="btn btn-default" style="margin-top: 20px;">Regresar a formularios</button>
      <% end %>
    </div><!-- /.table-responsive -->
  </div><!-- /.box-body -->
</div>