config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'pages#home'

  namespace :admin do
    resources :collectors
    resources :forms
    resources :form_responses, only: [:show]
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :forms, only: [:index]
      resources :sessions, only: [:create,:destroy]
      resources :form_responses, only: [:create]
      resources :sessions, only: [:create] do
        collection do
          delete :destroy
        end
      end
    end
  end

end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to  root_path, class: "navbar-brand" do %>
        <%= image_tag "header-logo.png" ,class: 'logo-header' %>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <% if current_user.admin? %>
          <li><%= link_to 'Dashboard', root_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Asesores<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Nuevo Asesor', new_admin_collector_path %></li>
                <li><%= link_to 'Mis Asesores', admin_collectors_path %></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Formularios<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Nuevo Formulario', new_admin_form_path %></li>
                <li><%= link_to 'Mis Formularios', admin_forms_path %></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email.split('@')[0] %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete %></li>
          <% end %>

        <% else %>
          <% if params[:controller] != 'devise/sessions' && params[:action] != 'new' %>
          <li><%= link_to "Iniciar Sesión", new_user_session_path %></li>
          <% end %>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Harvest Data</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js' %>


  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>
<%= yield %>

</body>
</html>